services:
  giga-webcheck-api:
    image: giga-webcheck-api:v3
    ports:
      - "8086:3000"
    volumes:
      # - app:/app
      - app2:/home/node/app
volumes:
  # app:
  app2:
#     driver: local
